version: '3.4'

networks:
  request:

services:
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: cert_nginx
    volumes:
      - ./docker/infra/cert:/var/www
      - ./docker/infra/cert/default.conf:/etc/nginx/conf.d/config.template:ro
      - ./docker/logs/nginx:/var/log/nginx
    networks:
      - request
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: ${HOST}
    cap_add:
      - SYS_TIME
    restart: always
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
