version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: ./
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - 6379

  celery-worker:
    build: ./
    mem_reservation: 2GB
    command: celery -A pele worker --beat -l INFO
    depends_on:
      - redis

volumes:
  postgres_data:
  static_value:
  media_value:
