version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: ./
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  celery-worker:
    build: ./
    mem_reservation: 2GB
    command: celery -A pele worker --beat -l INFO
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis

  flower:
    build: ./
    mem_reservation: 2GB
    command: celery -A pele flower
    ports:
      - "5555:5555"
    depends_on:
      - redis

  nginx:
    image: nginx:1.19.8-alpine
    expose:
      - 80
      - 443
      - 8081
      - 8082
      - 8083
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./docker/infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./pele/static:/var/html/static
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
