# Generated by Django 4.1.2 on 2022-10-23 14:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.CharField(blank=True, help_text='Field for setting comments about yourhaircut', max_length=300, verbose_name='Comments of the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Field for getting phone number of theclient', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
