# Generated by Django 4.1.2 on 2022-10-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Barber of this appointment'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time_begin', 'time_end', 'barber')},
        ),
    ]
