# Generated by Django 4.1.2 on 2022-11-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='comment_sr',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_sr',
        ),
    ]
