# Generated by Django 4.1.2 on 2022-11-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_en',
            field=models.TextField(choices=[('auth_user', 'Auth user'), ('admin', 'Admin user'), ('barber_user', 'Barber user')], default='auth_user', null=True, verbose_name='User role'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_sr',
            field=models.TextField(choices=[('auth_user', 'Auth user'), ('admin', 'Admin user'), ('barber_user', 'Barber user')], default='auth_user', null=True, verbose_name='User role'),
        ),
    ]
