# Generated by Django 4.1.2 on 2022-11-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_en_user_role_sr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_sr',
        ),
    ]
